modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="horsenbt"
version="${file.jarVersion}"
displayName="HorseNBT"
credits="Made by Zeldown"
authors="Zeldown"
description='''
$Minecraft Forge Additional Entity Data
'''
[[dependencies.horsenbt]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.horsenbt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"